
// 195 countries:
// 193 UN member states + Palestine + Vatican City.
// Wadiya is fictional and is included separately.

const COUNTRY_CODES = {
  // Africa
  algeria: "dz",
  angola: "ao",
  benin: "bj",
  botswana: "bw",
  "burkina faso": "bf",
  burundi: "bi",
  "cabo verde": "cv",
  cameroon: "cm",
  "central african republic": "cf",
  chad: "td",
  comoros: "km",
  "democratic republic of the congo": "cd",
  "republic of the congo": "cg",
  "cote d'ivoire": "ci",
  djibouti: "dj",
  egypt: "eg",
  "equatorial guinea": "gq",
  eritrea: "er",
  eswatini: "sz",
  ethiopia: "et",
  gabon: "ga",
  gambia: "gm",
  ghana: "gh",
  guinea: "gn",
  "guinea-bissau": "gw",
  kenya: "ke",
  lesotho: "ls",
  liberia: "lr",
  libya: "ly",
  madagascar: "mg",
  malawi: "mw",
  mali: "ml",
  mauritania: "mr",
  mauritius: "mu",
  morocco: "ma",
  mozambique: "mz",
  namibia: "na",
  niger: "ne",
  nigeria: "ng",
  rwanda: "rw",
  "sao tome and principe": "st",
  senegal: "sn",
  seychelles: "sc",
  "sierra leone": "sl",
  somalia: "so",
  "south africa": "za",
  "south sudan": "ss",
  sudan: "sd",
  tanzania: "tz",
  togo: "tg",
  tunisia: "tn",
  uganda: "ug",
  zambia: "zm",
  zimbabwe: "zw",

  // Americas
  "antigua and barbuda": "ag",
  argentina: "ar",
  bahamas: "bs",
  barbados: "bb",
  belize: "bz",
  bolivia: "bo",
  brazil: "br",
  canada: "ca",
  chile: "cl",
  colombia: "co",
  "costa rica": "cr",
  cuba: "cu",
  dominica: "dm",
  "dominican republic": "do",
  ecuador: "ec",
  "el salvador": "sv",
  grenada: "gd",
  guatemala: "gt",
  guyana: "gy",
  haiti: "ht",
  honduras: "hn",
  jamaica: "jm",
  mexico: "mx",
  nicaragua: "ni",
  panama: "pa",
  paraguay: "py",
  peru: "pe",
  "saint kitts and nevis": "kn",
  "saint lucia": "lc",
  "saint vincent and the grenadines": "vc",
  suriname: "sr",
  "trinidad and tobago": "tt",
  united_states: "us",
  uruguay: "uy",
  venezuela: "ve",

  // Europe
  albania: "al",
  andorra: "ad",
  austria: "at",
  belarus: "by",
  belgium: "be",
  "bosnia and herzegovina": "ba",
  bulgaria: "bg",
  croatia: "hr",
  cyprus: "cy",
  czechia: "cz",
  denmark: "dk",
  estonia: "ee",
  finland: "fi",
  france: "fr",
  germany: "de",
  greece: "gr",
  hungary: "hu",
  iceland: "is",
  ireland: "ie",
  italy: "it",
  latvia: "lv",
  liechtenstein: "li",
  lithuania: "lt",
  luxembourg: "lu",
  malta: "mt",
  moldova: "md",
  monaco: "mc",
  montenegro: "me",
  netherlands: "nl",
  north_macedonia: "mk",
  norway: "no",
  poland: "pl",
  portugal: "pt",
  romania: "ro",
  russia: "ru",
  "san marino": "sm",
  serbia: "rs",
  slovakia: "sk",
  slovenia: "si",
  spain: "es",
  sweden: "se",
  switzerland: "ch",
  turkey: "tr",
  ukraine: "ua",
  united_kingdom: "gb",
  "vatican city": "va",

  // Asia
  afghanistan: "af",
  armenia: "am",
  azerbaijan: "az",
  bahrain: "bh",
  bangladesh: "bd",
  bhutan: "bt",
  brunei: "bn",
  cambodia: "kh",
  china: "cn",
  georgia: "ge",
  india: "in",
  indonesia: "id",
  iran: "ir",
  iraq: "iq",
  israel: "il",
  japan: "jp",
  jordan: "jo",
  kazakhstan: "kz",
  kuwait: "kw",
  kyrgyzstan: "kg",
  laos: "la",
  lebanon: "lb",
  malaysia: "my",
  maldives: "mv",
  mongolia: "mn",
  myanmar: "mm",
  nepal: "np",
  "north korea": "kp",
  oman: "om",
  pakistan: "pk",
  palestine: "ps",
  philippines: "ph",
  qatar: "qa",
  "saudi arabia": "sa",
  singapore: "sg",
  "south korea": "kr",
  "sri lanka": "lk",
  syria: "sy",
  tajikistan: "tj",
  thailand: "th",
  "timor-leste": "tl",
  turkmenistan: "tm",
  "united arab emirates": "ae",
  uzbekistan: "uz",
  vietnam: "vn",
  yemen: "ye",

  // Oceania
  australia: "au",
  fiji: "fj",
  kiribati: "ki",
  "marshall islands": "mh",
  micronesia: "fm",
  nauru: "nr",
  "new zealand": "nz",
  palau: "pw",
  "papua new guinea": "pg",
  samoa: "ws",
  "solomon islands": "sb",
  tonga: "to",
  tuvalu: "tv",
  vanuatu: "vu",

  // Fictional
  wadiya: "wadiya",
};


// Common aliases.
// These point to the canonical country names above.
const COUNTRY_ALIASES = {
  usa: "united_states",
  "united states": "united_states",
  "u.s.": "united_states",
  "u.s.a.": "united_states",
  america: "united_states",

  uk: "united_kingdom",
  "great britain": "united_kingdom",

  "czech republic": "czechia",

  "cape verde": "cabo verde",

  "ivory coast": "cote d'ivoire",

  "democratic republic of congo": "democratic republic of the congo",
  drc: "democratic republic of the congo",

  congo: "republic of the congo",

  swaziland: "eswatini",

  "east timor": "timor-leste",

  "south korea": "south korea",
  "republic of korea": "south korea",

  "north korea": "north korea",

  uae: "united arab emirates",

  türkiye: "turkey",

  vatican: "vatican city",
  "holy see": "vatican city",

  "state of palestine": "palestine",

  wadiya: "wadiya",
};


// Flag emojis for the 195 countries.
const COUNTRY_FLAGS = {
  algeria: "🇩🇿",
  angola: "🇦🇴",
  benin: "🇧🇯",
  botswana: "🇧🇼",
  "burkina faso": "🇧🇫",
  burundi: "🇧🇮",
  "cabo verde": "🇨🇻",
  cameroon: "🇨🇲",
  "central african republic": "🇨🇫",
  chad: "🇹🇩",
  "comoros": "🇰🇲",
  "democratic republic of the congo": "🇨🇩",
  "republic of the congo": "🇨🇬",
  "cote d'ivoire": "🇨🇮",
  djibouti: "🇩🇯",
  egypt: "🇪🇬",
  "equatorial guinea": "🇬🇶",
  eritrea: "🇪🇷",
  eswatini: "🇸🇿",
  ethiopia: "🇪🇹",
  gabon: "🇬🇦",
  gambia: "🇬🇲",
  ghana: "🇬🇭",
  guinea: "🇬🇳",
  "guinea-bissau": "🇬🇼",
  kenya: "🇰🇪",
  lesotho: "🇱🇸",
  liberia: "🇱🇷",
  libya: "🇱🇾",
  madagascar: "🇲🇬",
  malawi: "🇲🇼",
  mali: "🇲🇱",
  mauritania: "🇲🇷",
  mauritius: "🇲🇺",
  morocco: "🇲🇦",
  mozambique: "🇲🇿",
  namibia: "🇳🇦",
  niger: "🇳🇪",
  nigeria: "🇳🇬",
  rwanda: "🇷🇼",
  "sao tome and principe": "🇸🇹",
  senegal: "🇸🇳",
  seychelles: "🇸🇨",
  "sierra leone": "🇸🇱",
  somalia: "🇸🇴",
  "south africa": "🇿🇦",
  "south sudan": "🇸🇸",
  sudan: "🇸🇩",
  tanzania: "🇹🇿",
  togo: "🇹🇬",
  tunisia: "🇹🇳",
  uganda: "🇺🇬",
  zambia: "🇿🇲",
  zimbabwe: "🇿🇼",

  "antigua and barbuda": "🇦🇬",
  argentina: "🇦🇷",
  bahamas: "🇧🇸",
  barbados: "🇧🇧",
  belize: "🇧🇿",
  bolivia: "🇧🇴",
  brazil: "🇧🇷",
  canada: "🇨🇦",
  chile: "🇨🇱",
  colombia: "🇨🇴",
  "costa rica": "🇨🇷",
  cuba: "🇨🇺",
  dominica: "🇩🇲",
  "dominican republic": "🇩🇴",
  ecuador: "🇪🇨",
  "el salvador": "🇸🇻",
  grenada: "🇬🇩",
  guatemala: "🇬🇹",
  guyana: "🇬🇾",
  haiti: "🇭🇹",
  honduras: "🇭🇳",
  jamaica: "🇯🇲",
  mexico: "🇲🇽",
  nicaragua: "🇳🇮",
  panama: "🇵🇦",
  paraguay: "🇵🇾",
  peru: "🇵🇪",
  "saint kitts and nevis": "🇰🇳",
  "saint lucia": "🇱🇨",
  "saint vincent and the grenadines": "🇻🇨",
  suriname: "🇸🇷",
  "trinidad and tobago": "🇹🇹",
  united_states: "🇺🇸",
  uruguay: "🇺🇾",
  venezuela: "🇻🇪",

  albania: "🇦🇱",
  andorra: "🇦🇩",
  austria: "🇦🇹",
  belarus: "🇧🇾",
  belgium: "🇧🇪",
  "bosnia and herzegovina": "🇧🇦",
  bulgaria: "🇧🇬",
  croatia: "🇭🇷",
  cyprus: "🇨🇾",
  czechia: "🇨🇿",
  denmark: "🇩🇰",
  estonia: "🇪🇪",
  finland: "🇫🇮",
  france: "🇫🇷",
  germany: "🇩🇪",
  greece: "🇬🇷",
  hungary: "🇭🇺",
  iceland: "🇮🇸",
  ireland: "🇮🇪",
  italy: "🇮🇹",
  latvia: "🇱🇻",
  liechtenstein: "🇱🇮",
  lithuania: "🇱🇹",
  luxembourg: "🇱🇺",
  malta: "🇲🇹",
  moldova: "🇲🇩",
  monaco: "🇲🇨",
  montenegro: "🇲🇪",
  netherlands: "🇳🇱",
  north_macedonia: "🇲🇰",
  norway: "🇳🇴",
  poland: "🇵🇱",
  portugal: "🇵🇹",
  romania: "🇷🇴",
  russia: "🇷🇺",
  "san marino": "🇸🇲",
  serbia: "🇷🇸",
  slovakia: "🇸🇰",
  slovenia: "🇸🇮",
  spain: "🇪🇸",
  sweden: "🇸🇪",
  switzerland: "🇨🇭",
  turkey: "🇹🇷",
  ukraine: "🇺🇦",
  united_kingdom: "🇬🇧",
  "vatican city": "🇻🇦",

  afghanistan: "🇦🇫",
  armenia: "🇦🇲",
  azerbaijan: "🇦🇿",
  bahrain: "🇧🇭",
  bangladesh: "🇧🇩",
  bhutan: "🇧🇹",
  brunei: "🇧🇳",
  cambodia: "🇰🇭",
  china: "🇨🇳",
  georgia: "🇬🇪",
  india: "🇮🇳",
  indonesia: "🇮🇩",
  iran: "🇮🇷",
  iraq: "🇮🇶",
  israel: "🇮🇱",
  japan: "🇯🇵",
  jordan: "🇯🇴",
  kazakhstan: "🇰🇿",
  kuwait: "🇰🇼",
  kyrgyzstan: "🇰🇬",
  laos: "🇱🇦",
  lebanon: "🇱🇧",
  malaysia: "🇲🇾",
  maldives: "🇲🇻",
  mongolia: "🇲🇳",
  myanmar: "🇲🇲",
  nepal: "🇳🇵",
  "north korea": "🇰🇵",
  oman: "🇴🇲",
  pakistan: "🇵🇰",
  palestine: "🇵🇸",
  philippines: "🇵🇭",
  qatar: "🇶🇦",
  "saudi arabia": "🇸🇦",
  singapore: "🇸🇬",
  "south korea": "🇰🇷",
  "sri lanka": "🇱🇰",
  syria: "🇸🇾",
  tajikistan: "🇹🇯",
  thailand: "🇹🇭",
  "timor-leste": "🇹🇱",
  turkmenistan: "🇹🇲",
  "united arab emirates": "🇦🇪",
  uzbekistan: "🇺🇿",
  vietnam: "🇻🇳",
  yemen: "🇾🇪",

  australia: "🇦🇺",
  fiji: "🇫🇯",
  kiribati: "🇰🇮",
  "marshall islands": "🇲🇭",
  micronesia: "🇫🇲",
  nauru: "🇳🇷",
  "new zealand": "🇳🇿",
  palau: "🇵🇼",
  "papua new guinea": "🇵🇬",
  samoa: "🇼🇸",
  "solomon islands": "🇸🇧",
  tonga: "🇹🇴",
  tuvalu: "🇹🇻",
  vanuatu: "🇻🇺",

  wadiya: "🏴",
};


// Resolve aliases and return the canonical key.
function normalizeCountry(country) {
  if (!country) return null;

  const key = country.trim().toLowerCase();

  return COUNTRY_ALIASES[key] || key;
}


// Returns a flag emoji.
export function countryToFlag(country) {
  const key = normalizeCountry(country);

  if (!key) return "🌐";

  return COUNTRY_FLAGS[key] || "🌐";
}


// Returns a real flag image URL from flagcdn.com.
export function countryToFlagImage(country, size = 160) {
  const key = normalizeCountry(country);

  if (!key) return null;

  const code = COUNTRY_CODES[key];

  if (!code || code === "wadiya") {
    return null;
  }

  return `https://flagcdn.com/w${size}/${code}.png`;
}
